version: "3"
services:    
  web:
    build:
      context: "./nginx/"
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - php
      - db
    image: ${PROJECT_NAME}-web
    container_name: ${PROJECT_NAME}-web

  php:
    build:
      context: "./php-fpm/"
    volumes:
      - "${APP_DIR}:/var/www/html"
    image: ${PROJECT_NAME}-php
    container_name: ${PROJECT_NAME}-php
    
  db:
    build:
      context: "./mysql/"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_HOST=127.0.0.1
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER_NAME}
      - MYSQL_PASSWORD=${USER_PASSWORD}
    ports:
        - ${DB_PORT}:3306
    image: ${PROJECT_NAME}-db
    container_name: ${PROJECT_NAME}-db
